### ISSUE TITLE
Extractor not working for Universal_Robots_ROS_Driver

### ISSUE THREAD

**Issue by ipa-nhg** [ipa320/ros-model-cloud#32]
Repo: https://github.com/UniversalRobots/Universal_Robots_ROS_Driver
distro: kinetic (because or ur_description and ur_msgs dependencies)
package: ur_robot_driver
node: ur_robot_driver_node

ERROR:

```
Traceback (most recent call last):

  File "/usr/local/bin/haros", line 8, in <module>

    sys.exit(main())

  File "/usr/local/lib/python2.7/dist-packages/haros/haros.py", line 904, in main

    if launcher.launch(argv = argv):

  File "/usr/local/lib/python2.7/dist-packages/haros/haros.py", line 170, in launch

    self.minimal_output = args.minimal_output

AttributeError: 'Namespace' object has no attribute 'minimal_output'

Traceback (most recent call last):

  File "/root/extractor-interface/scripts/ros_model_extractor.py", line 479, in <module>

    main()

  File "/root/extractor-interface/scripts/ros_model_extractor.py", line 474, in main

    if extractor.launch():

  File "/root/extractor-interface/scripts/ros_model_extractor.py", line 51, in launch

    self.extract_node(self.args.name, self.args.name, self.args.package_name, None, ws, None)

  File "/root/extractor-interface/scripts/ros_model_extractor.py", line 120, in extract_node

    self.extract_primitives(node, parser, analysis, rosmodel, roscomponent, pkg_name, node_name, node_name)

  File "/root/extractor-interface/scripts/ros_model_extractor.py", line 165, in extract_primitives

    srv_type = analysis._extract_message_type(call)

  File "/usr/local/lib/python2.7/dist-packages/haros/extractor.py", line 1349, in _extract_message_type

    assert re.match(r"\w+::\w+$", template)
```

**Comment by duda1202** [comment]
Hi,

I am having the same issue of not extracting properly with my own local files and it gives me this error:

```####
####

#### Running command: "cmake /home/core_uc/ros-model-cloud/extractor-interface/workspaces/ck85va6v00003315mi4wlr3ep/src -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCATKIN_DEVEL_PREFIX=/home/core_uc/ros-model-cloud/extractor-interface/workspaces/ck85va6v00003315mi4wlr3ep/devel -DCMAKE_INSTALL_PREFIX=/home/core_uc/ros-model-cloud/extractor-interface/workspaces/ck85va6v00003315mi4wlr3ep/install -G Unix Makefiles" in "/home/core_uc/ros-model-cloud/extractor-interface/workspaces/ck85va6v00003315mi4wlr3ep/build"

####

####

#### Running command: "make -j12 -l12" in "/home/core_uc/ros-model-cloud/extractor-interface/workspaces/ck85va6v00003315mi4wlr3ep/build"

####

Traceback (most recent call last):

  File "/home/core_uc/ros-model-cloud/extractor-interface/venv/bin/haros", line 8, in <module>

    sys.exit(main())

  File "/home/core_uc/ros-model-cloud/extractor-interface/venv/local/lib/python2.7/site-packages/haros/haros.py", line 904, in main

    if launcher.launch(argv = argv):

  File "/home/core_uc/ros-model-cloud/extractor-interface/venv/local/lib/python2.7/site-packages/haros/haros.py", line 170, in launch

    self.minimal_output = args.minimal_output

AttributeError: 'Namespace' object has no attribute 'minimal_output'

No handlers could be found for logger "haros.cmake_parser"

{'status_code': 500, 'message': {'errors': {'body': 'NO_MODEL_GENERATED', 'payload': ''}}}

```

I tried with a couple of different ROS packages available in github and they all gave me the same issue.

**Comment by ipa-nhg** [comment]
@duda1202 could you please specify the name of the packages and the GitHub repositories that you wanted to analyze? 

Usually the problem I find is because missed released dependencies of the repository to be analysed, issue that is quite hard to solve. But if this is also your case I will have to focus on this soon.

Thanks a lot for your time and your feedback! :)

**Comment by duda1202** [comment]
Hi,

A couple are my own locally developed packages that are not in github repositories as it is a university project. The others I tried mostly to see if it was working. Examples are:

* https://github.com/angusleigh/leg_tracker
* https://github.com/ROBOTIS-GIT/turtlebot3
* https://github.com/spencer-project
* https://github.com/IntelRealSense/realsense-ros

Is there another way of extracting the model besides the model extract using ros-model-cloud, for example by hand? Thanks!

**Comment by ipa-nhg** [comment]
I will check the projects you propose and try to find a solution. 
In case you are looking for the `realsense_node` description I have made already some experiments with this component: https://github.com/ipa-nhg/ros-model-experiments/blob/cob4/cob4-25/cob4-25_static/rosnodes/realsense.ros

The other method I can suggest, in case you have a running version of the nodes, is the use of the ros_graph_parser, a ros node that running in the same ROS master as the software to be analyzed can output the model as a file: https://github.com/ipa-led/ros_graph_parser

Also you have the option of playing locally with the static extractor infrastructure using the local installation setup https://github.com/ipa320/ros-model-cloud#local-testing , but probably make more sense that I firstly take a look at the repositories you proposes to give you some hints, the extractor repository is quite complex and my code not **yet** well documented :(

**Comment by ipa-nhg** [comment]
Fixed by #40 

Tested for melodic (docu https://github.com/ipa320/ros-model-cloud/blob/b3f203c8e335c794aabea8765344756d426b53da/docker/melodic/README.md) and I got:

```
PackageSet {
  CatkinPackage ur_robot_driver { 
    Artifact ur_robot_driver_node {
      Node { name ur_robot_driver_node
        ServiceServers {
          ServiceServer { name 'program_running' service 'ur_dashboard_msgs.IsProgramRunning'},
          ServiceServer { name 'hand_back_control' service 'std_srvs.Trigger'},
          ServiceServer { name 'zero_ftsensor' service 'std_srvs.Trigger'},
          ServiceServer { name 'resend_robot_program' service 'std_srvs.Trigger'},
          ServiceServer { name 'program_saved' service 'ur_dashboard_msgs.IsProgramSaved'},
          ServiceServer { name 'get_safety_mode' service 'ur_dashboard_msgs.GetSafetyMode'},
          ServiceServer { name 'load_installation' service 'ur_dashboard_msgs.Load.'},
          ServiceServer { name 'connect' service 'std_srvs.Trigger.'},
          ServiceServer { name 'add_to_log' service 'ur_dashboard_msgs.AddToLog.'},
          ServiceServer { name 'set_payload' service 'ur_msgs.SetPayload.'},
          ServiceServer { name 'popup' service 'ur_dashboard_msgs.Popup.'},
          ServiceServer { name 'load_program' service 'ur_dashboard_msgs.Load.'},
          ServiceServer { name 'raw_request' service 'ur_dashboard_msgs.Raw.'},
          ServiceServer { name 'program_state' service 'ur_dashboard_msgs.GetProgramState.'},
          ServiceServer { name 'get_loaded_program' service 'ur_dashboard_msgs.GetLoadedProgram.'},
          ServiceServer { name '?' service 'std_srvs.Trigger.'},
          ServiceServer { name 'quit' service 'std_srvs.Trigger.'},
          ServiceServer { name 'set_io' service 'ur_msgs.SetIO'},
          ServiceServer { name 'get_robot_mode' service 'ur_dashboard_msgs.GetRobotMode'},
          ServiceServer { name 'set_speed_slider' service 'ur_msgs.SetSpeedSliderFraction'}}
        Publishers {
          Publisher { name 'robot_program_running' message 'std_msgs.Bool'}}
        Subscribers {
          Subscriber { name 'script_command' message 'std_msgs.String'}}}}
}}
```
